---
- hosts: localhost
  gather_facts: no
  tasks:

  - name: Run docker ps command showing all running processes
    shell: docker ps

  - name: Run docker compose down command
    shell: docker-compose -f docker-compose-build.yml down

  - name: Cleanup resources using docker system Prune command
    shell: echo Y | docker system prune