apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: corewebapi
  # namespace: my-project
  labels:
    run: corewebapi

spec:
  replicas: 1
  selector:
    matchLabels:
      run: corewebapi
  
  template:
    metadata:
      labels:
        run: corewebapi
    spec:
      initContainers:
        - name: init-myservice
          image: nileshgule/sqlclient
          # command: ['sh', '-c', "/opt/mssql-tools/bin/sqlcmd -S mssql-deployment -U sa -P January2018 -d master -i initialize-database.sql"]
          command:
            - "sh"
            - "-c"
            - "/opt/mssql-tools/bin/sqlcmd -S mssql-deployment -U sa -P January2018 -d master -i initialize-database.sql"
      containers:
      - name: corewebapi
        image: nileshgule/corewebapi
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst